name: Lint, Validate, and Test
on:
  push:
    branches: [ main ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'development'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r tests/requirements.txt

      - name: Lint with autopep8
        run: |
            autopep8 --in-place --recursive --aggressive --aggressive src
            autopep8 --in-place --recursive --aggressive --aggressive tests

  Security:
    runs-on: ubuntu-latest
    needs:
      - Lint
    env:
      ENVIRONMENT: 'development'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r tests/requirements.txt

#      - name: Run Snyk to check for vulnerabilities
#        uses: snyk/actions/node@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          command: test --file=tests/requirements.txt --command=python3

  Integration:
    runs-on: ubuntu-latest
    needs:
      - Security
    env:
      ENVIRONMENT: 'development'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r tests/requirements.txt

      - name: Integration Tests
        run: |
          pytest tests -v